{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  # ClusterIP porque Postgres solo debe ser accesible desde dentro del cluster,
  # no expuesto al exterior como los microservicios.
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
{{- end }}
