apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  namespace: xhoswi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
        - name: streaming-service
          image: xhoswi/streaming-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: VIDEOS_DIR
              value: "/app/videos"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: xhoswi
spec:
  type: NodePort
  selector:
    app: streaming-service
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30003
